import streamlit as st
import mammoth
import weasyprint
import base64
from bs4 import BeautifulSoup
import tempfile
import os

st.set_page_config(page_title="AMC NTEP Manual Generator", layout="wide")
st.title("AMC NTEP - Official Booklet Generator")
st.write("Upload your Gujarati Word document to generate a formatted PDF manual.")

# --- Helper Function: Convert local image to Base64 ---
# WeasyPrint works best with logos when they are embedded directly as base64 data
def get_image_base64(filepath):
    if os.path.exists(filepath):
        with open(filepath, "rb") as image_file:
            encoded_string = base64.b64encode(image_file.read()).decode()
            mime_type = "image/png" if filepath.lower().endswith(".png") else "image/jpeg"
            return f"data:{mime_type};base64,{encoded_string}"
    return ""

# Read the logos you uploaded to GitHub
# Replace these filenames if you rename them in your repository
amc_logo_b64 = get_image_base64("Amdavad_Municipal_Corporation_logo.png")
ntep_logo_b64 = get_image_base64("1-s2.0-S0019570720303152-gr1.jpg") # Assuming this is the NTEP logo

# --- UI: File Upload ---
uploaded_docx = st.file_uploader("Upload Content Word Document (.docx)", type=["docx"])

if uploaded_docx is not None:
    with st.spinner("Extracting Gujarati content..."):
        with tempfile.NamedTemporaryFile(delete=False, suffix=".docx") as tmp_docx:
            tmp_docx.write(uploaded_docx.read())
            tmp_docx_path = tmp_docx.name

        with open(tmp_docx_path, "rb") as docx_file:
            result = mammoth.convert_to_html(docx_file)
            raw_html = result.value
        os.remove(tmp_docx_path) 

    with st.spinner("Applying Government Manual Formatting..."):
        soup = BeautifulSoup(raw_html, 'html.parser')

        # Build the HTML with Gujarati Font and Fixed Header for Logos
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                /* Import Gujarati Font from Google Fonts */
                @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Gujarati:wght@400;700&display=swap');
                
                /* Base Booklet Styles */
                body {{ 
                    font-family: 'Noto Sans Gujarati', sans-serif; 
                    line-height: 1.6; 
                    color: #000; 
                    text-align: justify;
                }}
                
                /* Page Layout & Margins */
                @page {{
                    size: A4;
                    /* Top margin is large (3.5cm) to make room for the fixed header logos */
                    margin: 3.5cm 2cm 2cm 2cm;
                    @bottom-center {{ 
                        content: counter(page); 
                        font-family: 'Arial', sans-serif;
                    }}
                }}
                
                /* Fixed Header for Logos on EVERY Page */
                header {{ 
                    position: fixed; 
                    top: -2.5cm; /* Push header up into the margin space */
                    left: 0px; 
                    right: 0px; 
                    height: 2cm; 
                    border-bottom: 2px solid #000;
                    padding-bottom: 10px;
                }}
                
                .logo-left {{ float: left; height: 60px; max-width: 150px; object-fit: contain; }}
                .logo-right {{ float: right; height: 60px; max-width: 150px; object-fit: contain; }}
                
                .header-title {{ 
                    text-align: center; 
                    font-weight: bold; 
                    padding-top: 20px; 
                    font-size: 16px; 
                }}
                
                /* Government Document Formatting */
                h1, h2, h3 {{ color: #000; font-weight: bold; }}
                h1 {{ 
                    page-break-before: always; /* Start new modules on a new page */
                    border-bottom: 1px solid #ccc; 
                    padding-bottom: 5px;
                }}
                
                /* Ensure lists match the screenshots */
                ul, ol {{ margin-left: 20px; padding-left: 10px; }}
                li {{ margin-bottom: 8px; }}
                
                /* Fix tables for data */
                table {{ width: 100%; border-collapse: collapse; margin-top: 15px; margin-bottom: 15px; }}
                th, td {{ border: 1px solid #000; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; font-weight: bold; }}
                
            </style>
        </head>
        <body>
            <!-- This header repeats on every page generated by WeasyPrint -->
            <header>
                <img src="{ntep_logo_b64}" class="logo-left" alt="NTEP Logo">
                <img src="{amc_logo_b64}" class="logo-right" alt="AMC Logo">
                <div class="header-title">રાષ્ટ્રીય ક્ષયરોગ નિવારણ કાર્યક્રમ (NTEP) - AMC</div>
            </header>
            
            <!-- The Extracted Word Document Content -->
            <div class="content">
                {str(soup)}
            </div>
        </body>
        </html>
        """

    with st.spinner("Generating PDF (This may take a moment to download fonts)..."):
        pdf_bytes = weasyprint.HTML(string=full_html).write_pdf()

    st.success("Manual Generated Successfully!")
    
    st.download_button(
        label="📄 Download Official PDF Manual",
        data=pdf_bytes,
        file_name="AMC_NTEP_Operational_Manual.pdf",
        mime="application/pdf"
    )
